apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  interval: 1h
  releaseName: oauth2-proxy
  targetNamespace: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      version: "10.1.4"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: oauth2-proxy
      interval: 12h
  values:
    # OIDC provider configuration (Casdoor)
    extraArgs:
      provider: oidc
      oidc-issuer-url: https://id.${BASE_DOMAIN:=libre.pod}
      redirect-url: https://oauth2-proxy.${BASE_DOMAIN:=libre.pod}/oauth2/callback
      cookie-domain: .${BASE_DOMAIN:=libre.pod}
      whitelist-domain: .${BASE_DOMAIN:=libre.pod}
      email-domain: "*"
      upstream: file:///dev/null
      pass-authorization-header: "true"
      set-authorization-header: "true"
      pass-user-headers: "true"
      set-xauthrequest: "true"
      reverse-proxy: "true"
      ssl-insecure-skip-verify: "true"
      skip-provider-button: "true"
      insecure-oidc-allow-unverified-email: "true"
    config:
      # Cookie secret for session encryption
      cookieSecret: "lWaxDZwT2kzBWfBN8kHi7KXficScqcnwHNRuLhhywzs="
      clientID: "librepod"
      clientSecret: "1cbc02ef6a9e7144f64e09385f0a21185c129819"
