apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: marketplace-ui
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/librepod/marketplace/apps/marketplace-ui
  ref:
    tag: "0.1.0"
  verify:
    provider: cosign
    secretRef:
      name: cosign-pub
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: marketplace-ui
  namespace: flux-system
spec:
  dependsOn:
    - name: gogs
    - name: cert-manager
  interval: 1m
  retryInterval: 2m
  timeout: 5m
  sourceRef:
    kind: OCIRepository
    name: marketplace-ui
  path: ./overlays/librepod
  prune: true
  wait: true
  postBuild:
    substitute:
      BASE_DOMAIN: "${BASE_DOMAIN}"
