apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dolt-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # No storageClassName here — patched in by overlay
