apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

buildMetadata:
- managedByLabel

namespace: open-webui

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: open-webui

resources:
  - namespace.yaml
  - helmrepository.yaml
  - externalsecret.yaml
  - pvc.yaml
