apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - coredns-custom.yaml
  - flux-ingressroute.yaml
  - traefik-tlsstore.yaml
  - certificate.yaml
  - cosign-pub.yaml
  - openbao-clustersecretstore.yaml
