apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - marketplace.librepod.org_ssoclients.yaml
  - role.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
