apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: litellm
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - kind: Rule
    match: Host(`litellm.${BASE_DOMAIN:=libre.pod}`)
    priority: 1
    services:
    - name: litellm
      port: 4000
