apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openbao

resources:
- ../../base
- ingressroute.yaml
- certificate.yaml

images:
- name: openbao/openbao
  newTag: 2.7.1

patches:
- path: ./patch-helmrelease.yaml
  target:
    kind: HelmRelease
- path: ./patch-storage-class.yaml
  target:
    kind: PersistentVolumeClaim
