apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-webui

resources:
  - ../../base
  - ingressroute.yaml
  - helmrelease.yaml
  - ssoclient.yaml
  - externalsecret-ca.yaml

patches:
  - path: patch-pvc.yaml
    target:
      kind: PersistentVolumeClaim
