apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-webui

resources:
  - ../../base
  - ingressroute.yaml
  - helmrelease.yaml
  - ssoclient.yaml

configMapGenerator:
- name: step-certificates-certs
  options:
    disableNameSuffixHash: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflects: "step-ca/step-certificates-certs"

patches:
  - path: patch-pvc.yaml
    target:
      kind: PersistentVolumeClaim
