apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: remnawave

resources:
- ../../base
- ../../components/postgres
- ingressroute.yaml

images:
- name: remnawave/backend
  newTag: "2.7.4"
- name: postgres
  newTag: "17.6"
- name: valkey/valkey
  newTag: "9-alpine"

patches:
- path: ./patch-storage-class.yaml
  target:
    kind: PersistentVolumeClaim
