apiVersion: v1
kind: Service
metadata:
  name: rustdesk-server-oss-hbbr
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: hbbr
  ports:
    - name: relay
      port: 21117
      targetPort: 21117
      protocol: TCP
    - name: webclient-relay
      port: 21119
      targetPort: 21119
      protocol: TCP
