apiVersion: v1
kind: Service
metadata:
  name: rustdesk-server-oss
spec:
  type: ClusterIP
  ports:
    - name: nat-test
      port: 21115
      targetPort: 21115
      protocol: TCP
    - name: id-tcp
      port: 21116
      targetPort: 21116
      protocol: TCP
    - name: id-udp
      port: 21116
      targetPort: 21116
      protocol: UDP
    - name: relay
      port: 21117
      targetPort: 21117
      protocol: TCP
    - name: webclient
      port: 21118
      targetPort: 21118
      protocol: TCP
    - name: webclient-relay
      port: 21119
      targetPort: 21119
      protocol: TCP
