apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatus

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: gatus

resources:
- namespace.yaml
- helmrepository.yaml
- helmrelease.yaml
