[server]
DOMAIN = gogs.${BASE_DOMAIN:=libre.pod}
HTTP_PORT = 3000
EXTERNAL_URL = http://gogs.${BASE_DOMAIN:=libre.pod}/
DISABLE_SSH = false
START_SSH_SERVER = true
SSH_PORT = 22
SSH_LISTEN_PORT = 2222

[database]
TYPE = sqlite3
PATH = /data/gogs.db

; TYPE = postgres
; HOST = gogs-postgres:5432
; NAME = gogs
; USER = gogs
; PASSWORD = gogs

[repository]
ROOT = /data/git/gogs-repositories

[security]
INSTALL_LOCK = true

[auth]
REQUIRE_SIGNIN_VIEW = true
ENABLE_REVERSE_PROXY_AUTHENTICATION = true
REVERSE_PROXY_AUTHENTICATION_HEADER = X-Auth-Request-Email
ENABLE_REVERSE_PROXY_AUTO_REGISTRATION = true
