apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openbao

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: openbao

resources:
- namespace.yaml
- pvc.yaml
- serviceaccount-eso.yaml
- helmrepository.yaml
- helmrelease.yaml
