# PostgreSQL component for Remnawave
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: remnawave

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: postgres

configMapGenerator:
- name: remnawave-postgres-env
  envs:
  - postgres.env

resources:
- pvc.yaml
- deployment.yaml
- service.yaml
