apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-ui-env
data:
  PORT: "3000"
  CATALOG_PATH: "/data/catalog.yaml"
  GOGS_URL: "http://gogs.gogs.svc.cluster.local:80"
  ALLOWED_ORIGINS: "https://marketplace.${BASE_DOMAIN:=libre.pod}"
