apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: marketplace-ui

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: marketplace-ui

configMapGenerator:
- name: marketplace-ui-catalog
  files:
  - catalog.yaml
  options:
    disableNameSuffixHash: true

secretGenerator:
- name: gogs-auth
  options:
    disableNameSuffixHash: true
    annotations:
      reflector.v1.k8s.emberstack.com/reflects: "gogs/user-apps-source-auth"

resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- service.yaml
- deployment.yaml
