apiVersion: v1
kind: ServiceAccount
metadata:
  name: marketplace-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: marketplace-ui-flux-reader
rules:
  - apiGroups: ['kustomize.toolkit.fluxcd.io']
    resources: ['kustomizations']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['helm.toolkit.fluxcd.io']
    resources: ['helmreleases']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
  - apiGroups: ['source.toolkit.fluxcd.io']
    resources: ['ocirepositories']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: marketplace-ui-flux-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: marketplace-ui-flux-reader
subjects:
  - kind: ServiceAccount
    name: marketplace-ui
    namespace: marketplace-ui
