serverAddr = "${FRP_SERVER_ADDR}"
serverPort = ${FRP_SERVER_PORT}

# Optional unique identifier for this frpc instance.
# clientID = "${FRP_CLIENT_ID}"
# Proxy name will be changed to {user}.{proxy}
user = "${FRP_USER}"

auth.method = "token"
auth.tokenSource.type = "file"
auth.tokenSource.file.path = "/etc/frp/auth/token"

webServer.addr = "0.0.0.0"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin"

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = ${FRP_SSH_REMOTE_PORT}

[[proxies]]
name = "wg-easy"
type = "udp"
localIP = "127.0.0.1"
localPort = 51820
remotePort = ${FRP_WG_REMOTE_PORT}
