apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netronome

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: netronome

configMapGenerator:
- name: netronome
  envs:
  - netronome.env

resources:
- namespace.yaml
- secret.yaml
- pvc.yaml
- service.yaml
- deployment.yaml
