apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gogs

resources:
- ../../base
- ingressroute.yaml

images:
- name: gogs/gogs
  newTag: next-0.14
# - name: postgres
#   newTag: "16-alpine"

components:
- ../../components/bootstrap-admin
# - ../../components/postgres
