apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: oci://ghcr.io/traefik/helm/traefik
  ref:
    tag: "41.2.0"
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
