apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: casdoor
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: OCIRepository
    name: casdoor-helm-charts
  values:
    # There is a bug with user permissions to write to the default sqlite database
    # location: https://github.com/casdoor/casdoor-helm/issues/42
    # Hence we have to ovewrite config with our custom path to store the database,
    # i.e. dataSourceName:
    config: |
      appname = casdoor
      httpport = 8000
      runmode = release
      SessionOn = true
      copyrequestbody = true
      driverName = sqlite
      dataSourceName = file:/data/casdoor.db?cache=shared
      dbName = casdoor
      redisEndpoint =
      defaultStorageProvider =
      isCloudIntranet = false
      authState = "casdoor"
      socks5Proxy = ""
      verificationCodeTimeout = 10
      initScore = 0
      logPostOnly = true
      origin =
      enableGzip = true
      # initDataFile = /init_data.json
