apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: casdoor

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: casdoor

resources:
- namespace.yaml
- ocirepository.yaml
- helmrelease.yaml
- pvc.yaml
