---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: casdoor-helm-charts
spec:
  interval: 24h
  url: oci://registry-1.docker.io/casbin/casdoor-helm-charts
  ref:
    tag: "4.1.0"
