---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: casdoor-helm-charts
spec:
  interval: 24h
  url: oci://registry-1.docker.io/casbin/casdoor-helm-charts
  ref:
    semver: "3.106.*"
