#!/usr/bin/env bash
# Audits apps/ for metadata-schema conformance and version-declaration archetype.
# Exit 0 = all conform; non-zero = at least one schema violation (drift lint).
set -uo pipefail
cd "$(dirname "$0")/.."

REQUIRED="name displayName description category website version source templates dependencies icon"
FORBIDDEN="notes appVersion"
REPORT="docs/design/app-audit.md"
violations=0

{
  echo "# App Audit"
  echo
  echo "_Generated by \`scripts/audit-apps.sh\`._"
  echo
  echo "| App | Missing required | Forbidden keys | Version archetype |"
  echo "|-----|------------------|----------------|-------------------|"
} > "$REPORT"

for m in apps/*/metadata.yaml; do
  app=$(basename "$(dirname "$m")")
  keys=$(grep -E '^  [a-zA-Z]+:' "$m" | sed 's/:.*//;s/^  //')

  missing=""
  for k in $REQUIRED; do
    echo "$keys" | grep -qx "$k" || missing="$missing $k"
  done
  forbidden=""
  for k in $FORBIDDEN; do
    echo "$keys" | grep -qx "$k" && forbidden="$forbidden $k"
  done

  # Version archetype detection
  arche=""
  grep -rql 'newTag' "apps/$app/overlays" 2>/dev/null && arche="${arche}kustomize-images "
  [ -f "apps/$app/base/ocirepository.yaml" ] && arche="${arche}oci-chart "
  grep -rql 'kind: HelmRelease' "apps/$app/base" "apps/$app/overlays" 2>/dev/null && arche="${arche}helmrelease "
  # inline image tag in a Deployment, no images: transformer
  if [ -z "$(grep -rl 'newTag' "apps/$app/overlays" 2>/dev/null)" ] \
     && grep -rqE '^\s+image:\s+\S+:\S+' "apps/$app/base" 2>/dev/null; then
    arche="${arche}inline-image "
  fi
  # remote kustomize base pinned by git ref
  grep -rqE 'resources:|https://github.com/.*\?.*ref=' "apps/$app/base/kustomization.yaml" 2>/dev/null \
    && grep -rq 'github.com/.*ref=' "apps/$app/base/kustomization.yaml" 2>/dev/null \
    && arche="${arche}remote-base-gitref "
  [ -z "$arche" ] && arche="UNKNOWN"

  [ -n "$missing" ] && violations=$((violations+1))
  [ -n "$forbidden" ] && violations=$((violations+1))
  [ "$arche" = "UNKNOWN" ] && violations=$((violations+1))

  printf '| %s | %s | %s | %s |\n' "$app" "${missing:-–}" "${forbidden:-–}" "$arche" >> "$REPORT"
done

# Renovate datasource notes for the non-kustomize / non-native archetypes.
# Regenerated on every run so they survive the report rewrite.
cat >> "$REPORT" <<'NOTES'

## Renovate datasource notes

- nfs-provisioner: github-tags, depName=kubernetes-sigs/nfs-subdir-external-provisioner,
  extractVersion prefix "nfs-subdir-external-provisioner-" (the ?ref= tag in base/kustomization.yaml)
- immich: docker, depName=<immich app image> for spec.version; chart tracked natively via base/ocirepository.yaml
- step-certificates: annotate spec.version to the step-certificates image, not a sidecar
- marketplace-ui: docker, depName=<marketplace-ui image>; spec.version annotation drives it (inline-image base, no images: transformer)
NOTES

cat "$REPORT"
echo
if [ "$violations" -gt 0 ]; then
  echo "AUDIT: $violations violation(s) found." >&2
  exit 1
fi
echo "AUDIT: all apps conform."
