apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-server-oss-hbbs
spec:
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-server-oss-hbbr
spec:
  storageClassName: nfs-client
