apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
spec:
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-data
spec:
  storageClassName: nfs-client
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
spec:
  storageClassName: nfs-client
