#!/bin/sh
# One-time (idempotent) OpenBao bootstrap: init, KV v2 engine, Kubernetes
# auth, OIDC auth (Casdoor SSO), policies, roles. Runs in the bootstrap Job
# alongside the store-credentials container; they exchange state through
# /shared. Policies are site-specific: every *.hcl mounted at /policies
# (openbao-policies ConfigMap from the overlay) becomes an OpenBao policy
# named after the file. (The audit device is declared in the server config —
# see helmrelease.yaml.)
set -e

SA_DIR=/var/run/secrets/kubernetes.io/serviceaccount

# Wait until the status API answers, and capture the parsed value (the
# table prints "Initialized true|false" in every state, sealed included).
echo "waiting for the openbao API..."
until [ -n "$INITIALIZED" ]; do
  INITIALIZED="$(bao status 2>&1 | sed -n 's/^Initialized[[:space:]]*//p')"
  sleep 3
done

# Acquire a root token: reuse the one stored by a previous run if present,
# otherwise perform the one-time initialization.
for i in $(seq 1 60); do
  [ -f /shared/root-token ] && break
  [ -f /shared/no-secret ] && break
  sleep 1
done

# Cross-check the credentials handshake against actual server state: a
# mismatch means the data PVC or the credentials Secret was wiped behind
# the other's back, and neither can be regenerated by re-running this Job.
if [ -f /shared/root-token ]; then
  if [ "$INITIALIZED" != "true" ]; then
    # Credentials were restored (or a stale Secret survived) but the data
    # volume is empty: drop the seal-volume copy too, or the restore branch
    # would resurrect this dead token on every future run.
    rm -f /seal/credentials.json
    echo "ERROR: credentials exist but the server is not initialized (data PVC wiped?); removed the stale seal-volume credentials copy. Delete the openbao-credentials Secret and this Job, then re-apply for a fresh init." >&2
    exit 1
  fi
  # Already initialized: wait for auto-unseal (static seal) before
  # re-applying the configuration below.
  until bao status 2>&1 | grep -q "^Sealed[[:space:]]*false"; do
    sleep 3
  done
  BAO_TOKEN="$(cat /shared/root-token)"
elif [ -f /shared/no-secret ]; then
  if [ "$INITIALIZED" = "true" ]; then
    echo "ERROR: server is already initialized (data PVC survived) but no credentials could be found — both the openbao-credentials Secret and the seal-volume copy are gone, so the root token and recovery keys are unrecoverable. Wipe the data PVC (README 'Operational notes') and delete this Job." >&2
    exit 1
  fi
  echo "initializing openbao..."
  # A seal is configured, so no secret_shares/threshold (Shamir params) —
  # init returns recovery keys + root token.
  INIT_JSON="$(bao operator init -format=json)"
  printf '%s' "$INIT_JSON" > /shared/credentials.json
  touch /shared/done
  BAO_TOKEN="$(printf '%s' "$INIT_JSON" | sed -n 's/.*"root_token"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
else
  echo "ERROR: timed out waiting for credentials handshake" >&2
  exit 1
fi
export BAO_TOKEN

# KV v2 secrets engine at apps/
if ! bao secrets list -format=json | grep -q '"apps/"'; then
  bao secrets enable -path=apps kv-v2
fi

# Kubernetes auth method. No token_reviewer_jwt: the chart binds the server
# ServiceAccount to system:auth-delegator, so OpenBao reviews client tokens
# with its own auto-rotating SA token.
if ! bao auth list -format=json | grep -q '"kubernetes/"'; then
  bao auth enable kubernetes
fi
bao write auth/kubernetes/config \
  kubernetes_host="https://kubernetes.default.svc:443" \
  kubernetes_ca_cert=@"$SA_DIR/ca.crt"

# Policies: every mounted *.hcl becomes a policy named after its file.
for hcl in /policies/*.hcl; do
  [ -f "$hcl" ] || continue   # no policies ConfigMap (optional mount)
  bao policy write "$(basename "$hcl" .hcl)" "$hcl"
done

# Roles
bao write auth/kubernetes/role/external-secrets \
  bound_service_account_names=openbao-eso \
  bound_service_account_namespaces=openbao \
  policies=eso-read-apps ttl=20m

bao write auth/kubernetes/role/marketplace-ui \
  bound_service_account_names=marketplace-ui \
  bound_service_account_namespaces=marketplace-ui \
  policies=marketplace-ui-write-apps ttl=20m

# OIDC auth method (SSO login to the UI / bao CLI) backed by Casdoor.
# Credentials come from Secret/openbao-sso, provisioned by the
# casdoor-sso-controller from the SSOClient CR in the overlay; the
# non-optional volume mount keeps this pod Pending until it exists.
# Writing auth/oidc/config triggers an immediate discovery fetch against the
# IdP — the wait loop first lets Reflector fill the mirrored CA ConfigMap
# stub (it starts empty), or the fetch fails TLS verification.
for i in $(seq 1 30); do
  [ -s /ca/root_ca.crt ] && break
  sleep 2
done
if ! bao auth list -format=json | grep -q '"oidc/"'; then
  bao auth enable oidc
fi
bao write auth/oidc/config \
  oidc_client_id="$(cat /sso/client_id)" \
  oidc_client_secret="$(cat /sso/client_secret)" \
  default_role="admin-sso" \
  oidc_discovery_url="$SSO_DISCOVERY_URL"
# Platform model: every Casdoor login is a trusted cluster admin (same as
# the other SSO apps). allowed_redirect_uris must match the SSOClient CR's
# redirectUris exactly.
bao write auth/oidc/role/admin-sso \
  role_type="oidc" \
  user_claim="sub" \
  policies="admin,default" \
  oidc_scopes="openid,profile,email" \
  allowed_redirect_uris="$BAO_PUBLIC_ADDR/ui/vault/auth/oidc/oidc/callback,http://localhost:8250/oidc/callback"

# The audit device is declared in the server configuration (see
# helmrelease.yaml), not enabled via the API.

echo "openbao bootstrap complete"
