apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frp-operator
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: frp-operator
      sourceRef:
        kind: HelmRepository
        name: frp-operator-charts
      interval: 12h
  values:
    operator:
      replica: 1
