apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frp-operator
spec:
  interval: 12h
  install:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: OCIRepository
    name: frp-operator-charts
  # Override image since the published chart still references the upstream image.
  # TODO: remove that once we switch back to the upstream chart and docker image
  values:
    operator:
      image: ghcr.io/librepod/frp-operator
      tag: v0.0.0-pr.2
