apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frp-operator

resources:
- ../../base

patches:
# TODO: Switch to ./patch-helmrelease.yaml once the PR is merged.
- path: ./patch-helmrelease-fork.yaml
  target:
    kind: HelmRelease
- path: ./patch-helmrepository-fork.yaml
  target:
    kind: HelmRepository
