# Switch to forked OCI chart with fix for https://github.com/zufardhiyaulhaq/frp-operator/pull/17
# TODO: Revert to upstream HTTP repo once the PR is merged.
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: frp-operator-charts
spec:
  interval: 24h
  url: oci://ghcr.io/librepod/charts/frp-operator
  ref:
    tag: "0.0.0-pr.1"
