apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frp-operator
spec:
  chart:
    spec:
      # Fork chart with fix for https://github.com/zufardhiyaulhaq/frp-operator/pull/17
      # Revert to version "~1.5.0" once the PR is merged.
      version: "0.0.0-pr.1"
  # Override image since the published chart still references the upstream image.
  values:
    operator:
      image: ghcr.io/librepod/frp-operator
      tag: v0.7.0-librepod1
