apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: litellm
          image: litellm/litellm
          imagePullPolicy: IfNotPresent
          args:
            - "--config"
            - "/app/config.yaml"
          envFrom:
            - configMapRef:
                name: litellm-env
          env:
            - name: GENERIC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: litellm-sso
                  key: GENERIC_CLIENT_ID
            - name: GENERIC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: litellm-sso
                  key: GENERIC_CLIENT_SECRET
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 4000
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
          startupProbe:
            httpGet:
              path: /health/readiness
              port: 4000
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
            - name: data
              mountPath: /root/.config
      volumes:
        - name: config
          configMap:
            name: litellm-config
        - name: data
          persistentVolumeClaim:
            claimName: litellm-data
