apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: litellm

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: litellm

configMapGenerator:
- name: litellm-env
  envs:
  - litellm.env
- name: litellm-config
  files:
  - config.yaml

resources:
- namespace.yaml
- externalsecret.yaml
- pvc.yaml
- service.yaml
- deployment.yaml
