apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres-data
  labels:
    app.kubernetes.io/name: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
