apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: casdoor

resources:
- ../../base
- ingressroute.yaml

configMapGenerator:
  - name: casdoor-env
    literals:
      - dataSourceName=file:/data/casdoor.db?cache=shared
      - runmode=prod
    options:
      disableNameSuffixHash: true

patches:
- path: ./patch-helmrelease.yaml
  target:
    kind: HelmRelease
- path: ./patch-storage-class.yaml
  target:
    kind: PersistentVolumeClaim
