apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: casdoor

resources:
- ../../base
- ingressroute.yaml

# configMapGenerator:
# - name: init-data
#   files:
#     - ./init_data.json
#   options:
#     disableNameSuffixHash: true

patches:
- path: ./patch-helmrelease.yaml
  target:
    kind: HelmRelease
- path: ./patch-storage-class.yaml
  target:
    kind: PersistentVolumeClaim
