apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: casdoor
spec:
  values:
    extraVolumeMounts:
    - name: data
      mountPath: /data
    # - name: init-data
    #   mountPath: /init_data.json
    #   subPath: init_data.json

    extraVolumes:
    - name: data
      persistentVolumeClaim:
        claimName: casdoor-data
    # - name: init-data
    #   configMap:
    #     name: init-data
