# MySQL component for Seafile
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: seafile

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: mysql

configMapGenerator:
- name: mysql
  envs:
  - mysql.env

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
