apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingressroute.yaml
- ssoclient.yaml
- externalsecret-ca.yaml

namespace: vaultwarden

patches:
  - path: deployment-ca-patch.yaml

images:
- name: vaultwarden/server
  newTag: 1.37.0-alpine
