apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: tailscale/tailscale
    newTag: "v1.98.4"

patches:
  - path: ./patch-storage-class.yaml
    target:
      kind: PersistentVolumeClaim
