apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
  namespace: renovate
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
