apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headscale

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: headscale

configMapGenerator:
- name: headscale-config
  files:
  - config.yaml

resources:
- namespace.yaml
- pvc.yaml
- service.yaml
- deployment.yaml
